" === GVIM === "

if has("gui_running")
    "Fullscreen"
    set guifont=Bitstream\ Vera\ Sans\ Mono\ 9
    set guioptions=-L
    colorscheme ir_black
endif

" === END GVIM === "

colorscheme darkvim
set nocompatible
set backspace=indent,eol,start
set ruler
set showmode
set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab
set autoindent
set autowrite
set showmatch
set number
set enc=utf8
set fileencodings=utf-8,latin2
set nobackup
set nolist

" === autoclose === "
"inoremap [ []<left>
"inoremap ( ()<left>
"inoremap { {}<left>
"inoremap " ""<left>
"inoremap ' ''<left>
" === end autoclose === "

filetype plugin on
filetype indent on

syntax on

nmap     <C-t>          :tabnew<CR>
nmap     <C-c>          :tabclose<CR>
map     <C-h>       :tabprev<CR>
imap     <C-h>       <Esc>:tabprev<CR><insert>
map     <C-l>      :tabnext<CR>
imap     <C-l>      <Esc>:tabnext<CR><insert>


