" === GVIM === "

if has("gui_running")
    "Fullscreen"
    set guifont=Bitstream\ Vera\ Sans\ Mono\ 9
    set guioptions=-L
    colorscheme wombat
    set guioptions-=l
    set guioptions-=L
    set guioptions-=m
    set guioptions-=T
    set guioptions-=R
    set guioptions-=r
endif

" === END GVIM === "

colorscheme darkvim
set nocompatible
set backspace=indent,eol,start
set ruler
set showmode
set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab
set autoindent
set autowrite
set showmatch
set number
set enc=utf8
set fileencodings=utf-8,latin2
set nobackup
set noswapfile
set nolist
set colorcolumn=80

" === autoclose === "
"inoremap [ []<left>
"inoremap ( ()<left>
"inoremap { {}<left>
"inoremap " ""<left>
"inoremap ' ''<left>
" === end autoclose === "

filetype plugin on
filetype indent on

syntax on

nmap     <C-t>          :tabnew<CR>
nmap     <C-c>          :tabclose<CR>
nmap <C-S-tab> :tabprevious<CR>
nmap <C-tab> :tabnext<CR>
map <C-S-tab> :tabprevious<CR>
map <C-tab> :tabnext<CR>
imap <C-S-tab> <Esc>:tabprevious<CR>i
imap <C-tab> <Esc>:tabnext<CR>i
nmap    <C-i> :! python %<CR>
